#!/bin/sh

INTERNET_STATE="down"

check_internet() {
 /usr/bin/wget -q --spider http://google.com
 if [ $? -eq 0 ]; then
  echo "Internet is up."
  INTERNET_STATE="up"
 else
  echo "Internet is down."
  INTERNET_STATE="down"
 fi
}

check_internet
while [ "$INTERNET_STATE" != "up" ]
do
 sleep 10
 check_internet
done
